name: Test Setup

on:
  push:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Setup on ${{ matrix.image }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - debian:11
          # - ubuntu:20.04  # See issue #2
          - ubuntu:22.04

    container:
      image: ${{ matrix.image }}
      options: -u root

    env:
      DEBIAN_FRONTEND: noninteractive
      DOTFILES_COMMIT_SHA: ${{ github.sha }}

    steps:
      - name: Install prerequisites for running inside docker container
        run: apt update && apt install -y sudo git

      - run: sudo apt-get update && sudo apt-get -y install curl
      - run: /bin/bash -c "$( curl -fsSL https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/setup.sh )"
