name: Test Quickstart

on:
  push:

jobs:
  test:
    name: Quickstart ${{ matrix.image }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - debian:11
          - ubuntu:20.04
          - ubuntu:22.04

    container:
      image: ${{ matrix.image }}
      options: -u root

    env:
      DOTFILES_COMMIT_SHA: ${{ github.sha }}

    steps:
      - name: Remove sudo command
        shell: bash
        run: echo "alias sudo=''" >> ~/.bashrc

      - name: sudo apt-get update && sudo apt-get -y install curl
        shell: bash
        run: |
          cat ~/.bashrc
          source ~/.bashrc
          sudo apt-get update && sudo apt-get -y install curl
      
      - name: /bin/bash -c "$( curl -fsSL https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/setup.sh )"
        shell: bash
        run: |
          source ~/.bashrc
          /bin/bash -c "$( curl -fsSL https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/setup.sh )"