name: Test Setup

on:
  push:

defaults:
  run:
    shell: bash -l -eo pipefail {0}

jobs:
  test:
    name: Setup on ${{ matrix.image }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - debian:10
          - debian:11
          # - ubuntu:20.04  # See issue #2
          - ubuntu:22.04

    container:
      image: ${{ matrix.image }}
      options: -u root

    env:
      DEBIAN_FRONTEND: noninteractive
      DOTFILES_COMMIT_SHA: ${{ github.sha }}

    steps:
      - name: Debug info
        run: echo "Check the logs"
        env:
          GITHUB: ${{ toJson(github) }}
          JOB: ${{ toJSON(job) }}
          RUNNER: ${{ toJSON(runner) }}

      - name: Configure tzdata
        run: apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata
        #if: 

      - name: Install prerequisites for running inside docker container
        run: apt update && apt install -y sudo git

      - name: Install general prerequisites
        run: sudo apt-get update && sudo apt-get -y install curl

      # Pass Commit SHA here in case there are changes to setup.sh on the branch where action is running
      - name: Run setup script
        run: bash -c "$( curl -fsSL https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/setup.sh )"

      - name: Print out version numbers
        run: |-
          source ~/.bashrc
          exa --version
          docker --version
          dotnet --version
          nvm --version
