name: Test Quickstart

on:
  push:

defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  test:
    name: Quickstart ${{ matrix.image }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - debian:11
          - ubuntu:20.04
          - ubuntu:22.04

    container:
      image: ${{ matrix.image }}
      options: -u root

    env:
      DOTFILES_COMMIT_SHA: ${{ github.sha }}

    steps:
      - name: Remove sudo
        run: |
          echo "alias sudo=''" >> ~/.bashrc
          echo "alias sudo=''" >> /etc/profile

          echo "---------~/.bashrc---------"
          cat ~/.bashrc
          echo "---------/etc/profile---------"
          cat /etc/profile

      - name: sudo apt-get update && sudo apt-get -y install curl
        run: |
          alias sudo=''
          source ~/.bashrc
          sudo apt-get update && sudo apt-get -y install curl
      
      - name: /bin/bash -c "$( curl -fsSL https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/setup.sh )"
        run: |
          alias sudo=''
          source ~/.bashrc
          /bin/bash -c "$( curl -fsSL https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/setup.sh )"