name: Test Quickstart

on:
  push:

jobs:
  test:
    name: Quickstart ${{ matrix.image }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - debian:11
          - ubuntu:20.04
          - ubuntu:22.04

    container:
      image: ${{ matrix.image }}
      options: -u root

    env:
      DOTFILES_COMMIT_SHA: ${{ github.sha }}

    steps:
      - name: Run Quickstart commands
        shell: bash
        run: |
          # Remove sudo
          echo "#!/usr/bin/env bash" >> ~/.bashrc
          echo "alias sudo=''" >> ~/.bashrc
          chmod +x ~/.bashrc
          source ~/.bashrc

          sudo apt-get update && sudo apt-get -y install curl
          /bin/bash -c "$( curl -fsSL https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/setup.sh )"
          source ~/.dotfiles/_env.sh