name: Validate Editorconfig

on:
  push:
    branches:
      - '**'

jobs:
  validate-editor-config:
      name: Validate editor config
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v4
        - name: Setup node
          uses: actions/setup-node@v3
          with:
            node-version-file: '.nvmrc'
        - name: Setup editorconfig-checker
          run: npm i -g editorconfig-checker
        - name: Run editorconfig-checker
          run: editorconfig-checker
